#!/usr/bin/env perl
use strict;
use warnings;

my @args = @ARGV;

if (@args && $args[0] =~ m{(?:^|/)bookml/search_index\.pl\z}) {
  # BookML's bundled XML indexer can block on generated LaTeXML HTML.
  # The real index is generated by the workflow after the container exits.
  exit 0;
}

exec $^X, @args or die "cannot execute Perl command: $!";
